<a href="https://colab.research.google.com/github/TorresVST/regressao-linear/blob/Multipla/Regress%C3%A3o_Linear_multipla.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
y_vetor = [220,260,320]
x = np.array([[1, 50, 5],[1, 60, 6],[1, 80, 7]])

y = np.array(y_vetor).reshape(-1,1)
xt = np.transpose(x)
mult = xt@x
inv = np.linalg.inv(mult)
betas = inv@xt@y

no wolfram alpha: (transpose {{1,35,22},{1,42,27.5},{1,29,24},{1,50,30},{1,40,25.5},{1,55,28},{1,33,23},{1,48,26}} * {{1,35,22},{1,42,27.5},{1,29,24},{1,50,30},{1,40,25.5},{1,55,28},{1,33,23},{1,48,26}})^(-1) * transpose {{1,35,22},{1,42,27.5},{1,29,24},{1,50,30},{1,40,25.5},{1,55,28},{1,33,23},{1,48,26}} * {{180},{210},{190},{230},{200},{240},{185},{220}}

In [ ]:
print("A matriz de Y é\n", y)

print("\n\nA matriz X é\n", x)

print("\n\nA matriz X transposta é\n", xt)

print("\n\nA matriz resultante de X transposta multiplicado por X é\n", mult)

print("\n\nO inverso da multiplicação de matrizes acima é\n", inv)

print("\n\nOs betas são\n", betas)

A matriz de Y é
 [[220]
 [260]
 [320]]


A matriz X é
 [[ 1 50  5]
 [ 1 60  6]
 [ 1 80  7]]


A matriz X transposta é
 [[ 1  1  1]
 [50 60 80]
 [ 5  6  7]]


A matriz resultante de X transposta multiplicado por X é
 [[    3   190    18]
 [  190 12500  1170]
 [   18  1170   110]]


O inverso da multiplicação de matrizes acima é
 [[ 6.1e+01  1.6e+00 -2.7e+01]
 [ 1.6e+00  6.0e-02 -9.0e-01]
 [-2.7e+01 -9.0e-01  1.4e+01]]


Os betas são
 [[20.]
 [ 2.]
 [20.]]


In [ ]:
print(f"y = {betas[0,0]} + {betas[1,0]}*x1 + {betas[2,0]}*x2")

y = 19.99999999997955 + 1.9999999999988347*x1 + 20.000000000012108*x2
